/*CREATE DATABASE SHUVAM;

USE Coach_X ---FIXING THE DATA BASE

-----------------
CREATE TABLE EMPLOYEES
(
EMP_ID INT,
EMP_NAME VARCHAR(255),
EMP_DESIGNATION CHAR(100),
EMP_CITY VARCHAR(100),
EMP_SALARY MONEY
)*/

--CREATE DATABASE COACHXL_EARNING;
--USE DATABASE SHUVAM

--STEP1:
/*CREATE TABLE DEPERTMENT
(
DEPT_NO INT PRIMARY KEY,-------PAREMT TABLE
DEPT_NAME VARCHAR(100),--Size Decleration
CITY VARCHAR(255)
)*/
----------
SELECT *FROM [dbo].[DEPERTMENT] 
------
STEP 2:

INSERT INTO DEPERTMENT VALUES (10,'ADMIN','HYD')
INSERT INTO DEPERTMENT VALUES (20,'HR','PUNE')
INSERT INTO DEPERTMENT VALUES (30,'TESTING','MUMBAI')
--------------------------
STEP 3:

CREATE TABLE EMPLOYEE_DETAILS /*CHILD TABLE*/
(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(255),
SALARY MONEY,
DEPT_NO INT FOREIGN KEY REFERENCES DEPERTMENT(DEP_TNO)
)

SELECT * FROM EMPLOYEE_DETAILS

STEP 4:

INSERT INTO EMPLOYEE_DETAILS VALUES (10,'CHARLIE',10000,10),(102,'SHUVAM',25000,20),(103,'ROHUT',30000,30);

STEP 5: TESTING

INSERT INTO EMPLOYEE_DETAILS VALUES (104,'RUCHIKA',5000,30)

DROP TABLE EMPLOYEES /*TO DELETE THE TABLE */

SELECT * FROM DEPERTMENT
WHERE CITY = 'PUNE'

SELECT * FROM DEPERTMENT
WHERE DEPT_NO = 30

SELECT * FROM DEPERTMENT
WHERE DEPT_NO <> 30

SELECT * FROM DEPERTMENT
WHERE SALARY > 20000

