USE COACHX_LIVE
SELECT  * FROM [DBO].[CUSTOMERS_DERAILS]
SELECT *FROM [dbo].[EMPLOYEE]

CREATE TABLE BRANCH
(
B_CODE INT PRIMARY KEY,
B_NAME VARCHAR(100),
B_LOCATIONS VARCHAR(150)
)
----------------------------
SELECT*FROM BRANCH
-----------------------

/* TESTING */

BEGIN TRANSACTION ---SHOW TRANSACION ---
INSERT INTO BRANCH VALUES (101,'AXIS BANK','HYDERABAD')
INSERT INTO BRANCH VALUES (102,'SBI BANK','MUMBAI')
COMMIT 

BEGIN TRANSACTION
ROLLBACK

BEGIN TRANSACTION
INSERT INTO BRANCH VALUES (103,'IDBI BANK','PUNE')
INSERT INTO BRANCH VALUES (104,'HDFC BANK','HYD')
INSERT INTO BRANCH VALUES (105,'HDFC BANK','CHENNI')

BEGIN TRANSACTION
ROLLBACK

----------------------------
GRANT SELECT,UPDATE ON EMP_TABLE--GROUPS(TO CHECK )
TO SOME_USER , ANOTHER_USER

PROCEDURE , TRIGGERS -- PL/SQL
CTE,WINDOW,INDEX,LOGS,PRIMARY SYNTEX
---------------------------------
SELECT NAME FROM SYS.DATABASES --TO CHECK DB NAME 

EXEC sp_helpdb -- TO CHECK DB DETAILS

SELECT *FROM AGENT_123

CREATE TABLE DEPT_INFORMATION
(
ID INT PRIMARY KEY,
NAMES VARCHAR(100),
GENDER VARCHAR(50),
DEPT_ID INT
)

SELECT *FROM DEPT_INFORMATION
---------------------------------------
CREATE PROCEDURE SPGET_INFORMATION
AS 
BEGIN
SELECT NAMES,GENDER FROM DEPT_INFORMATION
END
-----------------------------------------
SPGET_DEPT_INFORMATION
EXEC SPGET_INFORMATION
EXECUTE SPGET_INFORMATION


CREATE PROC SPGET_DEPT_BYGENDER_AND_DEPTARTMENT
@GENDER VARCHAR(30),
@DEPT_ID INT
AS
BEGIN
	SELECT NAMES,GENDER,DEPT_ID FROM DEPT_INFORMATION
	WHERE GENDER = @GENDER AND DEPT_ID = @DEPT_ID
END

SPGET_DEPT_BYGENDER_AND_DEPTARTMENT @DEPT_ID = 1,@GENDER = 'MALE'
SPGET_DEPT_BYGENDER_AND_DEPTARTMENT @DEPT_ID = 2,@GENDER = 'FEMALE'

-------------------------
/* TRIGGERS */
-------------------------

CREATE TABLE MAIN
(
ID INT PRIMARY KEY,
SALARY INT
)

INSERT INTO MAIN VALUES (3,3000),(4,4000)

CREATE TABLE BACKUP_OF_MAIN --STRUCTURE ,COLUMN,DATATYPE(SAME)
(
ID INT PRIMARY KEY,
SALARY INT
)
---------------------------------
CREATE TRIGGER DBO.TRGINSTEADOFDELETE
ON [DBO].[MAIN]
FOR DELETE
AS
BEGIN
DECLARE  @IDTT INT
DECLARE @SALARYDD INT
SELECT @IDTT=ID ,@SALARYDD = SALARY FROM DELETED
INSERT INTO DBO.BACKUP_OF_MAIN VALUES (@IDTT,@SALARYDD)
END
-------------------------------------------------------
DELETE FROM MAIN WHERE ID =1;
----------------------------------------
SELECT *FROM BACKUP_OF_MAIN
SELECT *FROM MAIN
---------------------------------------
SELECT *FROM BRANCH --- NOT NULL -- 

ALTER TABLE MAIN
ALTER COLUMN ID INT NOT NULL 

ALTER TABLE BRANCH
ALTER COLUMN B_CODE INT NOT NULL 
ALTER TABLE BRANCH
ADD CONSTRAINT PK_ID PRIMARY KEY (B_CODE)
---------------------------------------------

SELECT NAME,SALARY,EMP_123.GENDER,GENDERS.GENDER_TOTAL,GENDERS.AVG_SAL,GENDERS.MIN_SAL,GENDERS.MAX_SAL
FROM EMP_123
INNER JOIN
SELECT GENDER,COUNT(*) AS GENDER_TOTAL,AVG(SALARY)AS AVG_SAL,MIN(SALARY)AS MIN_SAL,MAX(SALARY)AS MAX_SAL
FROM EMP_123
GROUP BY GENDER) AS GENDERS
ON GENDERS.GENDER=EMP_12.GENDER
-----------------------------------------------------------
SELECT NAME, SALARY, A.GENDER, GENDERS.GENDER_TOTAL, GENDERS.AVG_SAL,GENDERS.MIN_SAL, GENDERS.MAX_SAL
FROM  [dbo].[EMP_123] AS A
INNER JOIN
(SELECT GENDER, COUNT(*) AS GENDER_TOTAL, AVG(SALARY) AS AVG_SAL,MIN(SALARY) AS MIN_SAL,MAX(SALARY) AS MAX_SAL
FROM [EMP_TABLE_WINDOW]
GROUP BY GENDER) AS GENDERS
ON GENDERS.GENDER = A.GENDER