SELECT *FROM [dbo].[EMP]

/* WRITE A SQL QUERY TO DISPLAY MAXIMUM SALARY FROM EMP TABLE */

SELECT MAX(SALARY) FROM EMP

/* WRITE A SQL QUERY TO DISPLAY EMP_NAME,WHO IS TAKING MAXIMUM SALARY */

SELECT NAMES,SALARY FROM EMP
WHERE SALARY =
(SELECT MAX(SALARY) FROM EMP) 

/* WRITE A SQL QUERY TO DISPLAY EMP_NAME,
WHO IS TAKING MAXIMUM SALARY */

SELECT NAMES, MAX (SALARY) FROM EMP
GROUP BY NAMES

SELECT NAMES,SALARY FROM EMP----OUTER QUERY ---5000,CHARLIE
WHERE SALARY=
(SELECT MAX(SALARY) FROM EMP) --INNER QUERY -- 50000
-----------------------------------------------------
/* WRITE A SQL QUERY TO DISPLAY SECOND HIGHEST SALARY FROM EMP TABLE */
----------------------------
SELECT *FROM EMP
SELECT TOP 3* FROM EMP --- SELECT *FROM EMP LIMIT 100
--------------------------------------------------
SELECT MAX(SALARY)
FROM EMP
WHERE SALARY NOT IN (SELECT MAX(SALARY)FROM EMP
----------------------------------------------------

SELECT MAX(SALARY) AS SECOND_HIGHEST_SALARY FROM EMP ---40000
WHERE SALARY <> --40
(SELECT MAX(SALARY) FROM EMP) --40000
WHERE SALARY <> ---50
(SELECT MAX(SALARY) FROM EMP --50000
-----------------
SELECT MAX(SALARY) AS SALARY FROM EMP
WHERE SALARY <(SELECT MAX (SALARY) FROM EMP
WHERE SALARY < (SELECT MAX (SALARY) FROM EMP))

CREATE TABLE CUSTOMERS1 
(
CUS_ID INT PRIMARY KEY,
FRIST_NAME VARCHAR (100)
)

CREATE TABLE ORDERS
(
ORDER_ID INT,
CUS_ID INT FOREIGN KEY REFERENCES CUSTOMERS1 (CUS_ID),
AMOUNT MONEY
)

CREATE TABLE CUSTOMERS_DERAILS
(
CUS_ID INT,
FIRST_NAME CHAR(100),
LAST_NAME CHAR(100),
AGE INT,
COUNTRY CHAR(100)
)

SELECT *FROM CUSTOMERS_DERAILS

/*SELECT FIRST_NAME OF CUSTOMERS, WITH MAX CUSTOMER ID */

SELECT FIRST_NAME, MAX(CUS_ID) FROM CUSTOMERS_DERAILS
GROUP BY FIRST_NAME
ORDER BY FIRST_NAME DESC
-----------------------------------------
SELECT FIRST_NAME FROM CUSTOMERS_DERAILS
WHERE CUS_ID=
(SELECT MAX (CUS_ID) FROM CUSTOMERS_DERAILS);
-------------------------------------------------
/* ROWS WITH MIN OF AGE */
SELECT *FROM CUSTOMERS_DERAILS
WHERE AGE=
(SELECT MIN (AGE) FROM CUSTOMERS_DERAILS);

/* CUSTOMER WITH ORDER*/
SELECT*FROM CUSTOMERS1
SELECT*FROM ORDERS

SELECT CUS_ID ,FIRST_NAME FROM CUSTOMERS1
WHERE CUS_ID IN
(SELECT CUS_ID FROM ORDERS)

---------------------------------
---DISTINCT CUS_ID,FIRST_NAME,JOIN, WHO MADE THE ORDER --
-------------------------------------
SELECT DISTINCT C.CUS_ID,C.FIRST_NAME FROM CUSTOMERS1 C
INNER JOIN
ORDERS O
ON
C.CUS_ID = O.CUS_ID
ORDER BY C.CUS_ID